/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShellRouteImport } from './routes/_shell'
import { Route as ShellIndexRouteImport } from './routes/_shell/index'
import { Route as ShellSalesRouteImport } from './routes/_shell/sales'
import { Route as ShellProductsRouteImport } from './routes/_shell/products'
import { Route as ShellProductionRouteImport } from './routes/_shell/production'
import { Route as ShellInventoryRouteImport } from './routes/_shell/inventory'
import { Route as ShellAiRouteImport } from './routes/_shell/ai'

const ShellRoute = ShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellIndexRoute = ShellIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellSalesRoute = ShellSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => ShellRoute,
} as any)
const ShellProductsRoute = ShellProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => ShellRoute,
} as any)
const ShellProductionRoute = ShellProductionRouteImport.update({
  id: '/production',
  path: '/production',
  getParentRoute: () => ShellRoute,
} as any)
const ShellInventoryRoute = ShellInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => ShellRoute,
} as any)
const ShellAiRoute = ShellAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => ShellRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof ShellIndexRoute
  '/ai': typeof ShellAiRoute
  '/inventory': typeof ShellInventoryRoute
  '/production': typeof ShellProductionRoute
  '/products': typeof ShellProductsRoute
  '/sales': typeof ShellSalesRoute
}
export interface FileRoutesByTo {
  '/ai': typeof ShellAiRoute
  '/inventory': typeof ShellInventoryRoute
  '/production': typeof ShellProductionRoute
  '/products': typeof ShellProductsRoute
  '/sales': typeof ShellSalesRoute
  '/': typeof ShellIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_shell': typeof ShellRouteWithChildren
  '/_shell/ai': typeof ShellAiRoute
  '/_shell/inventory': typeof ShellInventoryRoute
  '/_shell/production': typeof ShellProductionRoute
  '/_shell/products': typeof ShellProductsRoute
  '/_shell/sales': typeof ShellSalesRoute
  '/_shell/': typeof ShellIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/ai' | '/inventory' | '/production' | '/products' | '/sales'
  fileRoutesByTo: FileRoutesByTo
  to: '/ai' | '/inventory' | '/production' | '/products' | '/sales' | '/'
  id:
    | '__root__'
    | '/_shell'
    | '/_shell/ai'
    | '/_shell/inventory'
    | '/_shell/production'
    | '/_shell/products'
    | '/_shell/sales'
    | '/_shell/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ShellRoute: typeof ShellRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/': {
      id: '/_shell/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ShellIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/sales': {
      id: '/_shell/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof ShellSalesRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/products': {
      id: '/_shell/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ShellProductsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/production': {
      id: '/_shell/production'
      path: '/production'
      fullPath: '/production'
      preLoaderRoute: typeof ShellProductionRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/inventory': {
      id: '/_shell/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof ShellInventoryRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/ai': {
      id: '/_shell/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof ShellAiRouteImport
      parentRoute: typeof ShellRoute
    }
  }
}

interface ShellRouteChildren {
  ShellAiRoute: typeof ShellAiRoute
  ShellInventoryRoute: typeof ShellInventoryRoute
  ShellProductionRoute: typeof ShellProductionRoute
  ShellProductsRoute: typeof ShellProductsRoute
  ShellSalesRoute: typeof ShellSalesRoute
  ShellIndexRoute: typeof ShellIndexRoute
}

const ShellRouteChildren: ShellRouteChildren = {
  ShellAiRoute: ShellAiRoute,
  ShellInventoryRoute: ShellInventoryRoute,
  ShellProductionRoute: ShellProductionRoute,
  ShellProductsRoute: ShellProductsRoute,
  ShellSalesRoute: ShellSalesRoute,
  ShellIndexRoute: ShellIndexRoute,
}

const ShellRouteWithChildren = ShellRoute._addFileChildren(ShellRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  ShellRoute: ShellRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
